### ISSUE TITLE
makeAlexGetByte and non-ASCII text

### ISSUE THREAD

**Issue by cocreature** [GaloisInc/alex-tools#2]
`makeAlexGetByte` currently requires that you provide a function `Char -> Word8`. However, this is not possible for non ASCII text. An easy solution to that would be to instead have `makeAlexGetByte` take a function `Char -> [Word8]`. I’m happy to make a PR if you like that solution but I wanted to ask first if there is some specific reason for the current behavior or if you have a better solution.

**Comment by glguy** [comment]
Hi, I know this reply is about 7 years late, but what you need to do is map various unicode character classes or characters to different Word8 values and then duplicate that mapping in your lexer file. Each Word8 isn't necessarily an ASCII value.
